// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsPlacesWeb.Data;

#nullable disable

namespace SportsPlacesWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Calendarios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<Guid>("IdEscenario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdEscenario")
                        .IsUnique();

                    b.ToTable("Calendarios");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Escenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<Guid>("SedesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sedes_id");

                    b.HasKey("Id")
                        .HasName("PK__Escenari__3213E83F8C58B69A");

                    b.HasIndex("SedesId");

                    b.ToTable("Escenario", (string)null);
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Notificaciones", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("FechaEnvio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_envio");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("mensaje");

                    b.Property<string>("TipoNotificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3213E83F...");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.ReportesDano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EscenarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("escenario_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Evidencia")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("evidencia");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sede_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__Reportes__3213E83F...");

                    b.HasIndex("EscenarioId");

                    b.HasIndex("SedeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ReportesDano", (string)null);
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Reservas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("EspacioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("espacio_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("HoraFin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__Reservas__3213E83F22689D38");

                    b.HasIndex("EspacioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Sede__3213E83F...");

                    b.ToTable("Sedes", (string)null);
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Correo_Institucional");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3213E83F5DB2BFD7");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Calendarios", b =>
                {
                    b.HasOne("SportsPlacesWeb.Data.Entity.Escenario", "Escenario")
                        .WithOne("Calendario")
                        .HasForeignKey("SportsPlacesWeb.Data.Entity.Calendarios", "IdEscenario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escenario");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Escenario", b =>
                {
                    b.HasOne("SportsPlacesWeb.Data.Entity.Sede", "Sede")
                        .WithMany("Escenarios")
                        .HasForeignKey("SedesId")
                        .IsRequired()
                        .HasConstraintName("FK_Espacio_Sedes");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Notificaciones", b =>
                {
                    b.HasOne("SportsPlacesWeb.Data.Entity.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Notificacion_Usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.ReportesDano", b =>
                {
                    b.HasOne("SportsPlacesWeb.Data.Entity.Escenario", "Escenario")
                        .WithMany("ReportesDanos")
                        .HasForeignKey("EscenarioId")
                        .IsRequired()
                        .HasConstraintName("FK_ReporteDano_Escenario");

                    b.HasOne("SportsPlacesWeb.Data.Entity.Sede", "Sede")
                        .WithMany("ReportesDano")
                        .HasForeignKey("SedeId")
                        .IsRequired()
                        .HasConstraintName("FK_ReporteDano_Sede");

                    b.HasOne("SportsPlacesWeb.Data.Entity.Usuario", "Usuario")
                        .WithMany("ReportesDano")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_ReporteDano_Usuario");

                    b.Navigation("Escenario");

                    b.Navigation("Sede");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Reservas", b =>
                {
                    b.HasOne("SportsPlacesWeb.Data.Entity.Escenario", "Espacio")
                        .WithMany("Reservas")
                        .HasForeignKey("EspacioId")
                        .IsRequired()
                        .HasConstraintName("FK_Reserva_Espacio");

                    b.HasOne("SportsPlacesWeb.Data.Entity.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Reserva_Usuario");

                    b.Navigation("Espacio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Escenario", b =>
                {
                    b.Navigation("Calendario")
                        .IsRequired();

                    b.Navigation("ReportesDanos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Sede", b =>
                {
                    b.Navigation("Escenarios");

                    b.Navigation("ReportesDano");
                });

            modelBuilder.Entity("SportsPlacesWeb.Data.Entity.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("ReportesDano");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
